### PR TITLE
Fix getShardID does not return more than 100 shards

### LINKED ISSUE #80: getShardIDs returns 100 shards at max
getShardIDs use "DescribeStream" just once which in turn only return 100 shards at max.
We need to call DescribeStream a few times to get all the shards, something like this [Retrieving Shards](https://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-retrieve-shards.html)
**Reference:**
https://github.com/aws/aws-sdk-go/blob/master/service/kinesis/api.go#L3891

### PR DESCRIPTION
**Pull request by lordfarhan40**
Revision 1:
Changes:
1. Now using ListShards API instead of DescribeStream since it gets up to 1000 shards per call.
Testing:
1. Unit Tests modified to include ListShards.
End --

Changes:
1. Get shardId now iterates over the responses from "DescribeStream" to create an array of shardIds till we reach a point where "HasMoreShards" is false.
2. Replaced the string literals "TRIM_HORIZON" and "AFTER_SEQUENCE_NUMBER" with constants present in kinesis library.

Testing:
1. Tested by fetching shards from a stream having more than 100 shards.
2. Unit Test Cases pass.
resolve #80

### CODE REVIEW

File: consumer.go [hunk 1]
```diff
@@ -241,20 +241,36 @@ func (c *Consumer) handleRecord(shardID string, r *Record, fn func(*Record) Scan
...
+
+		if len(shards) == 0 {
+			return ss, nil
+		}
+
+		for _, shard := range shards {
+			ss = append(ss, *shard.ShardId)
+		}
+
+		exclusiveStartShardId = shards[len(shards)-1].ShardId
```
Comment (harlow) [inline consumer.go]: wondering if `NextToken` might be better for itterator?

> // When the number of shards in the data stream is greater than the default
    // value for the MaxResults parameter, or if you explicitly specify a value
    // for MaxResults that is less than the number of shards in the data stream,
    // the response includes a pagination token named NextToken. You can specify
    // this NextToken value in a subsequent call to ListShards to list the next
    // set of shards.

Comment (harlow) [reply consumer.go]: or maybe: 
https://godoc.org/github.com/aws/aws-sdk-go/service/kinesis#Kinesis.DescribeStreamPages

Comment (harlow) [reply consumer.go]: something like this:

```go
func (c *Consumer) getShardIDs(streamName string) ([]string, error) {
	var ss []string

	err := c.client.DescribeStreamPages(
		&kinesis.DescribeStreamInput{
			StreamName: aws.String(streamName),
		},
		func(page *kinesis.DescribeStreamOutput, lastPage bool) bool {
			for _, shard := range page.StreamDescription.Shards {
				ss = append(ss, *shard.ShardId)
			}
			return true
		})

	return ss, err
}
```

File: consumer.go [hunk 2]
```diff
@@ -241,20 +241,36 @@ func (c *Consumer) handleRecord(shardID string, r *Record, fn func(*Record) Scan
 }
 
 func (c *Consumer) getShardIDs(streamName string) ([]string, error) {
```
Comment (harlow) [inline consumer.go]: hmm looks like my comment go deleted. 

how do you feel about using the built-in pagination functionality:

```go
func (c *Consumer) getShardIDs(streamName string) ([]string, error) {
	var ss []string

	err := c.client.DescribeStreamPages(
		&kinesis.DescribeStreamInput{
			StreamName: aws.String(streamName),
		},
		func(page *kinesis.DescribeStreamOutput, lastPage bool) bool {
			for _, shard := range page.StreamDescription.Shards {
				ss = append(ss, *shard.ShardId)
			}

			return !lastPage
		})

	return ss, err
}
```

**Comment by mfarhan08** [comment]
> thanks for the PR! I think it might be worth exploring `DescribeStreamPages` instead of having to create our own pagination. Let me know your thoughts

Thanks a lot for giving some time to review, and yes DescribeStreamPages is indeed a better way. However, I stumbled upon "ListShards" which actually does specifically what we want, also returns maximum of 1000 shards per request. Do let me know which should we pick up and I will be glad to do the send the next revision of PR :)

**Comment by harlow** [comment]
> Do let me know which should we pick up and I will be glad to do the send the next revision of PR :)

I'm good with either those. Please choose the one you like better and then we can get this merged 👍

**Comment by lordfarhan40** [comment]
> > Do let me know which should we pick up and I will be glad to do the send the next revision of PR :)
> 
> I'm good with either those. Please choose the one you like better and then we can get this merged 👍

Now using ListShards, please review when ever you get some time. Thanks

**Comment by harlow** [comment]
Looks great. thanks for the PR!
